### ISSUE TITLE
Add support for a custom  404 page

### ISSUE THREAD

**Issue by j-f1** [11ty/eleventy-dev-server#10]
Most static website hosts will look for a `404.html` page at the top level of the website and serve it (along with a 404 status code) when a page is not found. Eleventy supported this (with some manual tweaking) when using BrowserSync: https://www.11ty.dev/docs/quicktips/not-found/#with-serve. It would be great to have this built into the new dev server by default!

**Comment by zachleat** [comment]
Yeah, big +1 from me on this one too. I had this on my wishlist of features too

**Comment by zachleat** [comment]
Shipping with 1.0.0-canary.5 this will look for a `404.html` in your output folder and use that content when a 404 status code is encountered
