### ISSUE TITLE
Encoding issue in markdown when changing not-markdown

### ISSUE THREAD

**Issue by pavelloz** [11ty/eleventy-dev-server#11]
When I edit markdown and save page, encoding works great.

After that if i save any other file (including markdown that sits next to it) - it will break encoding in all OTHER files.

Both files are UTF-8.

Reproduce repository: https://github.com/pavelloz/e11ty-encoding

Video:
https://user-images.githubusercontent.com/546845/157993029-fb70d569-7d42-45c3-8a3e-2f1375c936d2.mov

**Comment by zachleat** [comment]
This will ship with Eleventy Dev Server 1.0.0-canary.4 (and Eleventy v2.0.0-canary.4)

**Comment by zachleat** [comment]
Note for later, the default encoding is `utf-8` but we could add support for others here https://nodejs.org/api/buffer.html#buffers-and-character-encodings and/or automate it using https://www.npmjs.com/package/chardet
