### ISSUE TITLE
Feature request: serveStatic (for-free passthroughCopy)

### ISSUE THREAD

**Issue by TigersWay** [11ty/eleventy-dev-server#12]
I have been using - quite a lot - the `serveStatic` feature of browsersync.

Despite being "minimal", could this new server propose the same feature?
Of course it's still possible to use browsersync.

**Comment by TigersWay** [comment]
That's exactly how I use it!
We sometimes have quite heavy `static` folder(s), it seems a little pointless to copy all the files again and again.

**Comment by epelc** [comment]
We would benefit from something like this too. Having to copy thousands of image files can be quite slow.

It'd be really nice if `eleventy.addPassthroughCopy()` had an option of not actually copying files during serve but only during build. ie just go check the source path for whatever wildcard is listed instead.

Having it support to existing api would be very helpful as older sites have a mix of directory layouts and do not have all your image/asset files in a nice top level folder.

**Comment by TigersWay** [comment]
Thank to @zachleat and his answer to #13, I simply tried the `serve-static` middleware for expressjs and it's working fine!
- It's then easy to swap from the [dev server & middleware] to [addPassthroughCopy] for production
- There's just one problem left, we can't - simply - filter the requested path/resources as expressjs is doing with `use`

**Comment by zachleat** [comment]
For-free passthrough copy was filed on core at https://github.com/11ty/eleventy/issues/2456 will be shipping with Eleventy 2.0.0-canary.12!

Closing this one as resolved—the dev server piece of this shipped with 1.0.0-canary.11.

Thank you!
