### ISSUE TITLE
Feature request: middleware

### ISSUE THREAD

**Issue by TigersWay** [11ty/eleventy-dev-server#13]
I have been using - quite a lot - the `middleware` feature of browsersync.

Despite being "minimal", could this new server propose the same feature?
Of course it's still possible to use browsersync.

**Comment by TigersWay** [comment]
I'm going to try it today then!! 👍

**Comment by TigersWay** [comment]
Sorry I haven't had so much time to check.... but my [own middleware](https://github.com/TigersWay/browsersync-images-middleware) gives 
```
[11ty] Unhandled rejection in promise: (more in DEBUG output)
[11ty] ware.bind is not a function (via TypeError)
[11ty]
[11ty] Original error stack trace: TypeError: ware.bind is not a function
[11ty]     at EleventyDevServer.onRequestHandler......
```
it may be on my side, but I have no trouble with browser-sync in Eleventy - old or new versions.

**Comment by zachleat** [comment]
Ahhhh, yeah I don’t think we support `object` for middleware. Only functions right now!

```
 middleware: [{
      route: '/img',
      handle: require('browsersync-images-middleware')('public')
    }],
```

That said I believe you can refactor it to use a function instead:

```js
function(req, res, next) {
  if(!req.url.startsWith("/img")) {
    next();
  }
  // do the thing
}

**Comment by TigersWay** [comment]
You're right I could refactor... But I believe I'm the only one using my own middleware 😬 and as browser-sync went back to an ok status, I won't bother.
Thanks anyway for your checking!
