### ISSUE TITLE
Cannot change port via `eleventyConfig.setServerConfig`: throws error

### ISSUE THREAD

**Issue by jeromecoupe** [11ty/eleventy-dev-server#14]
Eleventy v2.0.0-canary.3
Eleventy Dev Server 1.0.0-canary.3
MacOS: Monterrey (Apple M& Pro)

Probably missing something obvious here. Tried to change port using 

```js
module.exports = function(eleventyConfig) {
  // SERVER
  // -------------------------------
  eleventyConfig.setServerConfig({
    port: 3000
  });

  // CONFIG
  // -------------------------------
  return {
    markdownTemplateEngine: "njk",
    dir: {
      input: "src",
      output: "dist"
    }
  };
};
```

And I keep getting the following error message

```txt
[11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
[11ty] 1. Error in your Eleventy config file '/Users/jeromecoupe/data/sandboxes/test/.eleventy.js'. (via EleventyConfigError)
[11ty] 2. eleventyConfig.setServerConfig is not a function (via TypeError)
...
```

As soon as I remove the `setServerConfig` lines, everything is back to normal and I get a server running on port 8080 when running `npx eleventy --serve`.

**Comment by TigersWay** [comment]
Despite what the doc says, it seems to be `setServerOptions`.

**Comment by jeromecoupe** [comment]
Thank you , Zach.
