### ISSUE TITLE
[Firefox] `domdiff` doesn't apply new CSS classes to edited templates

### ISSUE THREAD

**Issue by mattrossman** [11ty/eleventy-dev-server#18]
## Description

Currently, `reload-client.js` can listen for changes to underlying CSS files and reload styles accordingly when `domdiff` is enabled.

This works when editing the CSS file directly (e.g. when editing an existing class), however styles do not reload when updating a template file to use a newly created CSS class.

## Minimal Reproduction:

Given a project using `@11ty/eleventy@2.0.0-canary.4` with the following files:

`index.html`:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <p class="foo">Hello world</p>
  </body>
</html>
```

`style.css`:
```css
.foo {
  color: red;
}
```

`.eleventy.js`:
```js
module.exports = function (eleventyConfig) {
  eleventyConfig.addPassthroughCopy("style.css")
}
```

Run `eleventy --serve` and open the webpage.

Add the following to `style.css`:

```css
.bar {
  color: blue;
}
```

Save the file.

Change `class="foo"` to `class="bar"` in `index.html` and save.

The text turns black, as though unstyled.

## Expected Behavior

The text should turn blue after the class is updated.

## Additional Info:

If `style.css` is re-saved with the same contents after the HTML is updated, then the new style is applied.

This issue is particularly problematic for users of Tailwind CSS which relies on generating many new utility classes during development.

**Comment by mattrossman** [comment]
This issue occurs in Firefox (98.0.1). I cannot reproduce it in Chrome-based Edge.

**Comment by zachleat** [comment]
Successfully reproduced this one! looks like the CSS update request is returning content with only one class inside

![image](https://user-images.githubusercontent.com/39355/159799075-0b1e1de3-03f4-4e36-814d-541633aa6ee8.png)

**Comment by zachleat** [comment]
A ha, got it.

1. `style.css` updates to `style.css?_11ty=1649877712089` to apply the CSS-only style update.
2. the dom differ then swaps this back to `style.css` because that’s what it got from the rendered template

**Comment by zachleat** [comment]
Shipping with 1.0.0-canary.8
