### ISSUE TITLE
Add CLI for this

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-dev-server#2]
Will allow this server to run standalone.

```
npx @11ty/eleventy-dev-server
```

**Comment by jeromecoupe** [comment]
Thanks for the work on this. IMHO CLI would indeed be a great addition in order to be able to use it when running asset pipelines with NPM scripts and the likes.

**Comment by zeroby0** [comment]
CLI would let it be used outside JS! For example, with Python, in combination with the Tailwind CLI.

`pester_list.append('zeroby0')`

**Comment by bhdzllr** [comment]
Thank you for the good work. Joining the "pester list", would be useful in npm scripts.

**Comment by zachleat** [comment]
This will ship with 1.0.0-canary.10
