### ISSUE TITLE
my live-reload isnt working over LAN

### ISSUE THREAD

**Issue by wommy** [11ty/eleventy-dev-server#20]
browser-sync works as expected,

the script shows up, but doesnt do anything, i need to manually refresh

i even toggled `domdiff` and dropped brave shields

first i thought it was a vite problem

let me know what more information i can give ya

**Comment by zachleat** [comment]
Are you using custom middleware? Are you getting error messages? Can you provide a network panel screenshot?

**Comment by wommy** [comment]
oh man, i completely had this long dialog with someone else about all the configs etc, and my only guess is he deleted the comment?

lemme dig everything up again

**Comment by wommy** [comment]
off the top of my head, the best case i could use to articulate the problem was that 
`ntl dev` failed to live reload with the new dev server.

**Comment by wommy** [comment]
i originally discovered this working on a new personal fork of eleventy-base-blog,
originally it started as a little trial for me to see if i could update to the new dev server, and then the vite plugin version

i recently set up a little development home server raspberry pi that ive been SSHing into. its really nice, as i can just pick up from another computer in my house, also alot tougher on data loss, because it rarely restarts.

on my client browser, i just hit IP:8080/path and hit it, without needing the flag to show that in the output

while on the point of flags, i found the domdiff / reload one, i even hard enabled the refresh with that other flag

i noticed that the vite wasnt live-reloading, after flipping a few lines in the config, i down-graded back to the normal new dev-server and noticed it was either

i even played with the debug output:
what i noticed was that everything was running fine, but that last line that marks the GET or whatever, wasnt being triggered over network somehow.

i even tried to repeat that bug where it wouldnt work without a head, but i believe that was fixed with the dev-server

**Comment by zachleat** [comment]
Shipping with 1.0.0-canary.9

**Comment by zachleat** [comment]
Shipped.
