### ISSUE TITLE
`await next()` with serverless middleware (middleware order)

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-dev-server#29]
For example, this configuration:

```js
const { EleventyServerlessBundlerPlugin } = require("@11ty/eleventy");

module.exports = function(eleventyConfig) {
  eleventyConfig.addPlugin(function(eleventyConfig) {
    eleventyConfig.setServerOptions({
      middleware: [async function customMiddleware(req, res, next) {
        let result = await next();
        console.log( {result} );
        return result;
      }],
    });
  });

  eleventyConfig.addPlugin(EleventyServerlessBundlerPlugin, {
    name: "possum", // The serverless function name from your permalink object
    functionsDir: "./netlify/functions/",
  });
};
```

Reported after a test case reproduction from https://twitter.com/peschee/status/1526312000321642497

**Comment by zachleat** [comment]
forgive me for cc-ing you here but I think @Holben888 and I might have talked about middleware ordering too

**Comment by zachleat** [comment]
I do want to note for future readers—a wrinkle here with middleware ordering when using `addPlugin`. Specifically the next two examples will have the same middleware order:

```js
module.exports = function(eleventyConfig) {
  eleventyConfig.setServerOptions({
    middleware: …
  });

  eleventyConfig.addPlugin(EleventyServerlessBundlerPlugin);
};
```

or

```js
module.exports = function(eleventyConfig) {
  eleventyConfig.addPlugin(EleventyServerlessBundlerPlugin);

  eleventyConfig.setServerOptions({
    middleware: …
  });
};
```

The above two snippets will always put the serverless plugin middleware second—why? Well, plugin execution happens in a second stage (after the primary config runs).

You can make an anonymous inline plugin to workaround this limitation (if this is what you want!)

```js
module.exports = function(eleventyConfig) {
  eleventyConfig.addPlugin(EleventyServerlessBundlerPlugin);

  eleventyConfig.addPlugin(function(eleventyConfig) {
    eleventyConfig.setServerOptions({
      middleware: …
    });
  });
};
```

**Comment by bholmesdev** [comment]
@zachleat Ah yep, we were discussing precedence ordering when other plugins are fighting the serverless plugin for middleware. I'm wondering if 11ty could use [Vite's plugin priority ordering](https://vitejs.dev/guide/api-plugin.html#transformindexhtml) when configuring this, where they offer an `enforce: 'pre' | 'post'` key 🤷

**Comment by zachleat** [comment]
Here’s a sample that can consume and modify serverless output (requires eleventy-dev-server `1.0.0-canary.10`)

```js
const { EleventyServerlessBundlerPlugin } = require("@11ty/eleventy");

module.exports = function(eleventyConfig) {
  eleventyConfig.addPlugin(EleventyServerlessBundlerPlugin, {
    name: "possum",
    functionsDir: "./netlify/functions/",
  });

  eleventyConfig.addPlugin(eleventyConfig => {
    eleventyConfig.setServerOptions({
      middleware: [function(req, res, next) {
        // This runs after the serverless middleware
        console.log( req.url, res.body );
        res.body += "Hello from middleware";
        res.end();
      }],
    });
  });
});
```

**Comment by zachleat** [comment]
Note that #30 was filed as a follow-up here.

This will ship with upcoming eleventy-dev-server `1.0.0-canary.10` (eleventy `2.0.0-canary.12`)
