### ISSUE TITLE
morphdom dependency error

### ISSUE THREAD

**Issue by ryangittings** [11ty/eleventy-dev-server#3]
On CSS save, getting the following:

```
[11ty] ENOENT: no such file or directory, open node_modules/@11ty/eleventy-dev-server/node_modules/morphdom/dist/morphdom-esm.js' (via Error)
```

Seems there is no node_modules folder within @11ty/eleventy-dev-server? Could be me being silly! Upgrading from 1.0.0 using the `npm install @11ty/eleventy@canary` command.

Cheers :)

**Comment by zachleat** [comment]
This will ship with `1.0.0-canary.2` thank you!
