### ISSUE TITLE
Eleventy@canary & pathprefix

### ISSUE THREAD

**Issue by TigersWay** [11ty/eleventy-dev-server#37]
**Describe the bug**
Following #2417 it appears that a trailing slash is missing in the given url from eleventy-dev-server with the last eleventy@canary

**To Reproduce**
Run an `eleventy --serve` with a pathprefix: npx eleventy --serve --pathprefix=SUBDIR
- eleventy@canary & eleventy-dev-server

the server is going to offer `http://localhost:8080/SUBDIR`

**Expected behavior**
the server should offer `http://localhost:8080/SUBDIR/`

**Environment:**
- Eleventy@canary

**Comment by pdehaan** [comment]
Ref: https://github.com/11ty/eleventy/discussions/2417 for more context.

**Comment by zachleat** [comment]
Shipping with dev-server 1.0.0-canary.14

There were a few bugs with pathPrefix, specifically around missing leading/trailing slashes on prefixes as well as file resolution wasn’t stripping the pathPrefix correctly!

**Comment by zachleat** [comment]
Shipping with Eleventy core 2.0.0-canary.15
