### ISSUE TITLE
Aliased directories and requests to `/` should return `/index.html`

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-dev-server#43]
> I figured it out – if the directory that is the target of a passthrough copy has subdirectories, the files do get served if you go to them directly, e.g. the URL http://localhost:8080/mobile-wiki/index.html will serve the index.html file. But the URLs http://localhost:8080/mobile-wiki and http://localhost:8080/mobile-wiki/ will not serve the index.html file if the passthrough copy behavior is "passthrough". Not sure if that qualifies as a bug, but definitely had me chasing this down for a while.

> Edit: Just noticed that this behavior can be reproduced in a simpler setting: 1. Make a passthrough rule that copies a directory, e.g. dir, over, and 2. make sure it has an index.html file inside it. Then if the copy behavior is "passthrough", visiting dir/ will 404 while visiting dir/index.html will not, but if copy behavior is "copy" then both will work.

https://github.com/11ty/eleventy/issues/2739#issuecomment-1378047701

cc @yurivish

**Comment by yurivish** [comment]
Thanks for filing this!

I also noticed that some other URLs don't resolve – e.g. `http://localhost:8080/cardcrafting/img_2x/2015-08-17%2014.19.27.jpg` is a 404. I think it's probably the space between the date and time, encoded as `%20`.

I get an error ("Cannot GET /cardcrafting/img_2x/2015-08-17%2014.19.27.jpg" with the dev server by default), but can get the image to load by putting the following ine in my config:

```
eleventyConfig.setServerPassthroughCopyBehavior("copy");
```

**Comment by zachleat** [comment]
I believe the second issue @yurivish is tracked at #59. The first issue seems to be resolved with Dev Server 2.0.0.
