### ISSUE TITLE
DOM diffing does not work

### ISSUE THREAD

**Issue by chalkygames123** [11ty/eleventy-dev-server#48]
Hi,

I'm having fun trying this brand-new dev server and have encountered unexpected behavior.

Am I missing something?

## What did I expect to happen:

Eleventy Dev Server that is bundled with Eleventy 2.0 will apply HTML changes without a full page reload.

## What actually happened:

The server triggers a full page reload with an output "Page reload initiated." in the browser console when updating the input file, even if the `domDiff` option is enabled.

## Steps to reproduce:

Create a new directory and then:

1. Run `npm install -DE @11ty/eleventy@2.0.0-canary.33`
2. Create `index.html`
3. Run `eleventy --serve`
4. Open `localhost:8080` in your browser
5. Edit and save `index.html`

Reproduction repo: https://github.com/chalkygames123/repro-eleventy-serve-dom-diffing

**Comment by zachleat** [comment]
You’re right! I’m on it.

**Comment by zachleat** [comment]
Regression from #41

**Comment by zachleat** [comment]
This will ship with Dev Server v1.0.2

**Comment by chalkygames123** [comment]
It's fast! Thank you 🥳
