### ISSUE TITLE
Server adds CSP header when serving custom 404 page

### ISSUE THREAD

**Issue by rothsandro** [11ty/eleventy-dev-server#55]
When serving the custom 404 page by calling a non-existing url, the Dev Server responds with a Content Security Policy header. This blocks some content like JS files.

<img width="1570" alt="csp" src="https://user-images.githubusercontent.com/16229645/220190377-818c10d0-62a3-4ccd-9f02-2a9232697177.png">

This only happens on the 404 page. On all other pages there are no CSP headers.

Repro: https://github.com/rothsandro/repro.eleventy-404-csp

**Comment by murtuzaalisurti** [comment]
I am also facing this issue

**Comment by bobmonsour** [comment]
There's a Discord thread on this too. Seems that it only happens when developing locally. Deployed sites run js on 404 pages. Here's a link to the thread:

https://discord.com/channels/741017160297611315/1068561825391714344

**Comment by xplosionmind** [comment]
I am having this problem too!

in my 404 page:

```
13:03:16.304 Loading failed for the <script> with source “https://visits.tommi.space/umami.js”. asfiqourfqo:313:1
13:03:16.315 Content Security Policy: The page’s settings blocked the loading of a resource at https://visits.tommi.space/umami.js (“script-src”). asfiqourfqo
13:03:16.315 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). asfiqourfqo:366:1
13:03:16.317 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
Source: javascript:history.go(-1) asfiqourfqo
13:03:16.371 [11ty][12:03:16.371 UTC] Connected asfiqourfqo:392:18
13:03:20.206 Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://99f4b94e-d4e8-4d51-8427-73faa1221a25/model/static/DOMPurify/purify.min.js
Source Map URL: purify.min.js.map
```

**Comment by zachleat** [comment]
Looking at this one today 🙌🏻

**Comment by zachleat** [comment]
This will roll up with dev server v1.0.4!

**Comment by xplosionmind** [comment]
Hi @zachleat, even after manually installing version 1.0.4 (since the one bundled into eleventy is not up to date), I still get these errors… do you have any idea why?

```
16:14:18.341 Loading failed for the <script> with source “http://localhost:8080/index.js”. whole-jam:10282:1
16:14:18.592 [11ty][15:14:18.592 UTC] Connected reload-client.js:21:18
16:14:25.469 Navigated to http://localhost:8080/whole-jam/
16:14:25.575 [11ty][15:14:25.575 UTC] Reconnecting… reload-client.js:21:18
16:14:25.674 GEThttp://localhost:8080/index.js
[HTTP/1.1 404 Not Found 2ms]

16:14:25.779 Loading failed for the <script> with source “http://localhost:8080/index.js”. whole-jam:10282:1
16:14:25.984 [11ty][15:14:25.985 UTC] Connected reload-client.js:21:18
```

**Comment by murtuzaalisurti** [comment]
> Hi @zachleat, even after manually installing version 1.0.4 (since the one bundled into eleventy is not up to date), I still get these errors… do you have any idea why?
> 
> ```
> 16:14:18.341 Loading failed for the <script> with source “http://localhost:8080/index.js”. whole-jam:10282:1
> 16:14:18.592 [11ty][15:14:18.592 UTC] Connected reload-client.js:21:18
> 16:14:25.469 Navigated to http://localhost:8080/whole-jam/
> 16:14:25.575 [11ty][15:14:25.575 UTC] Reconnecting… reload-client.js:21:18
> 16:14:25.674 GEThttp://localhost:8080/index.js
> [HTTP/1.1 404 Not Found 2ms]
> 
> 16:14:25.779 Loading failed for the <script> with source “http://localhost:8080/index.js”. whole-jam:10282:1
> 16:14:25.984 [11ty][15:14:25.985 UTC] Connected reload-client.js:21:18
> ```

it should work now, the `v1.0.4` is bundled with 11ty `v2.0.1`

**Comment by zachleat** [comment]
@murtuzaalisurti Can you use the `showVersion` dev server option to verify what dev server version is being used at run time? https://www.11ty.dev/docs/dev-server/#options

**Comment by zachleat** [comment]
@murtuzaalisurti can you test the repo above? it’s what I worked from to fix iirc https://github.com/rothsandro/repro.eleventy-404-csp Maybe I missed something!

**Comment by murtuzaalisurti** [comment]
> @murtuzaalisurti can you test the repo above? it’s what I worked from to fix iirc https://github.com/rothsandro/repro.eleventy-404-csp Maybe I missed something!

@zachleat  yeah, I was able to reproduce the error. It is evident in 11ty `v2.0.0` which bundles 11ty dev server `v1.0.3`

![Code_e5Pi0R5LPY](https://user-images.githubusercontent.com/68743212/228912004-db011d9d-c3f8-45a5-8deb-db4ecb1b1d1e.jpg)

![chrome_D9bk2gPTcM](https://user-images.githubusercontent.com/68743212/228912192-5940a9b5-9543-44b0-b1d9-2cee490f9b00.jpg)

**Comment by zachleat** [comment]
great! can you upgrade to 2.0.1 and help report if the issue persists locally?

**Comment by murtuzaalisurti** [comment]
> great! can you upgrade to 2.0.1 and help report if the issue persists locally?

no issues! works perfect.

**Comment by murtuzaalisurti** [comment]
@zachleat so, the expected behavior should be that 11ty `v2.0.0` or any 11ty version prior to `2.0.1` should bundle 11ty dev server version `1.0.4` or the latest, right?

**Comment by zachleat** [comment]
For 2.0.0 from a fresh install, yes. There are additional complexities around pre-installed dependencies or npm cache using an already available version that meets the package.json requirements for 2.0.0. But installing 2.0.1 should guarantee `@11ty/eleventy-dev-server` 1.0.4+

https://github.com/11ty/eleventy/blob/v2.0.1/package.json#L99
https://github.com/11ty/eleventy/blob/v2.0.0/package.json#L99

**Comment by murtuzaalisurti** [comment]
@zachleat yep, you are right, I tried running 11ty on stackblitz with `v2.0.0` and it bundles `v1.0.4` of dev server! I might need to clear npm cache I guess.

![chrome_EIv6Vx7Muh](https://user-images.githubusercontent.com/68743212/229270706-7f19dbd5-c40c-4d49-8825-3642f5ddc80a.jpg)
