### ISSUE TITLE
Redirects do not respect pathPrefix

### ISSUE THREAD

**Issue by simonpai** [11ty/eleventy-dev-server#56]
Given a pathPrefix = `"/abc/"`, the [server](https://github.com/11ty/eleventy-dev-server/blob/e8cb274b88c278b17d455dd5dd1b596a14b8581d/server.js#L277-L291) may redirect path `/abc/def` to `/def/`. We need to prepend the pathPrefix back for the new location.

**Comment by Aankhen** [comment]
We encountered this when debugging an issue on the Eleventy Discord. I put together an MWE:

https://github.com/Aankhen/eleventy-pathprefix-issue

**Comment by zachleat** [comment]
I believe this is a duplicate of #65, which was shipped with Dev Server 2.0
