### ISSUE TITLE
Attributes on <html> are removed

### ISSUE THREAD

**Issue by j-f1** [11ty/eleventy-dev-server#6]
In my layout file, I have the opening HTML tag written like this:

```html
<html lang="en" class="h-100" data-theme="dark">
```

When first loading the page, this all works fine.

However, whenever I change a file, and this message is printed in the browser console, all the attributes on the `<html>` tag are removed.

```
[Log] [11ty][22:34:28.851 UTC] – "HTML delta applied without page reload." (reload-client.js, line 21)
```

**Comment by zachleat** [comment]
Related https://github.com/patrick-steele-idem/morphdom/issues/39

**Comment by zachleat** [comment]
Shipping with `1.0.0-canary.2`
