### ISSUE TITLE
Deleted html templates can still be browsed to until the dev server is restarted

### ISSUE THREAD

**Issue by NathanBowers** [11ty/eleventy-dev-server#60]
Reproduce:

1. Have an eleventy project
2. Start dev server
3. Create a new file that would output html (md, njk, etc.)
4. Web browse to that file 
5. Delete the file
6. Notice that the file is still available in the browser until the dev server is restarted

Notes:
- Eleventy version: @11ty/eleventy@2.0.0
- Tried server with and without --incremental  and it didn't help.

**Comment by zachleat** [comment]
Shipping with Dev Server v2.0.1
