### ISSUE TITLE
Unwanted CSP when using Deno

### ISSUE THREAD

**Issue by vrugtehagel** [11ty/eleventy-dev-server#78]
I'd love to use Eleventy with Deno, but there's a small CSP-related issue with the dev server that prevents it from working out-of-the box.

Eleventy's dev server automatically [applies a CSP](https://github.com/11ty/eleventy-dev-server/blob/2e41ce7ab571192061c447d3f9e6a1c1590c3c94/server.js#L574) with a specific hash if the generated response is not 200 OK and not a custom error page. When running Eleventy with Deno, the `statusCode` seems to be `undefined` for successful responses (it does have `statusCode: 404` for paths that don't exist, but I didn't test beyond that). This `undefined` causes a restrictive CSP to be added to the page, which essentially blocks any JavaScript from running on the otherwise-normal page.

A simple solution to this issue is to treat `statusCode` being `undefined` as if it is `200`. Happy to open a PR for this or other proposed solutions.

Potentially, the issue lies with Deno; if this might be the case, I can pursue that route as well.

<details>
  <summary>Here are some details about my setup</summary>

```
project/
├── .eleventy.js
├── index.js
├── index.liquid
├── deno.json
└── package.json
```

The `index.liquid` file includes `<script src="index.js">`, and the script itself can contain anything, but a console log is simple enough to demonstrate the issue (it is not logged).

The `package.json` exists to avoid `require()` issues, and contains

```json
{
  "license": "UNLICENSED",
  "private": true,
  "type": "module"
}
```

My Eleventy config is rather simple, only passing through the `index.js` file and keeping the rest default:

```js
export default function(config) {
    config.addPassthroughCopy('./index.js')
}
```

My `deno.json` defines the serve and build tasks, as follows:

```json
{
  "tasks": {
    "serve": "deno run -A npm:@11ty/eleventy@^3.0.0-alpha.10 --serve",
    "build": "deno run -A npm:@11ty/eleventy@^3.0.0-alpha.10"
  }
}
```

The tasks do succeed just fine, the issue is merely that the server adds the restrictive CSP header.

</details>

**Comment by vrugtehagel** [comment]
On second thought, I think this issue might be better off being fixed in Deno; see https://github.com/denoland/deno/issues/23970. Leaving this open for now, to allow anyone to confirm which fix is the preferred one.

**Comment by vrugtehagel** [comment]
A fix has been introduced in Deno (see https://github.com/denoland/deno/pull/23977). Closing this issue - apologies for the noise!

**Comment by zachleat** [comment]
I appreciate the heads up either way! Thanks for circling back! 🙌🏻
