### ISSUE TITLE
404 when asset has space in filename

### ISSUE THREAD

**Issue by pavelloz** [11ty/eleventy-dev-server#8]
Hello,

Great job on the dev server, im it works great so far :)

It looks like if i request asset with spaces in name, it will 404.

### Files:
```
e11ty-space|master ⇒ ll app/assets/*.png
app/assets/my test image.png
app/assets/my-test-image.png
```

### Code:
```
  <img src="/assets/my test image.png" alt="">
  <br/>
  <img src="/assets/my-test-image.png" alt="">
```

### Result:
![image](https://user-images.githubusercontent.com/546845/157754524-3bf7d109-2de1-4119-bed0-af933e50c2ea.png)

## Reproduction repo: https://github.com/pavelloz/e11ty-dev-server-space

**Comment by zachleat** [comment]
Oops sorry about that! I linked up the wrong issue to close

**Comment by zachleat** [comment]
Shipping with 1.0.0-canary.3
