### ISSUE TITLE
Make shutdown process graceful

### ISSUE THREAD

**Issue by VividVisions** [11ty/eleventy-dev-server#84]
Currently, the web server, the update (WebSocket) server and the Chokidar watcher are closed by calling their respective `close()` functions, disregarding their callbacks/returned Promises. Furthermore `process.exit();` is called immediately after, preventing a graceful shutdown altogether.

I'd suggest to make the `close()` methods of `EleventyDevServer` and `Cli` asynchronous and to change `process.exit();` to `process.exitCode = 0;` in case of a `SIGINT` signal. This would make the shutdown process clean and graceful.

I'd happily provide a PR!

**Note**: These changes would also necessitate small adjustments in Eleventy itself, i.e. making `stopWatch()` of `Eleventy` asynchronous and exchanging `process.exit();` there as well.

<details>

<summary> Background:</summary>

We've built a custom server which wraps around `EleventyDevServer` and needs a bit of cleanup during shutdown. Due to the current shutdown process, we couldn't use the `close` event of `http.Server` which either doesn't even get emitted or isn't waited for. We had to implement ugly workarounds/hacks to make this work. ;)

</details>

**Comment by zachleat** [comment]
Happy to merge this but any API breaking changes in Eleventy core and we might be able to sneak it in to 3.0 if it happens _very soon_ (like, probably this week)

**Comment by VividVisions** [comment]
Created a PR. Please let me know if I should change anything.
I'll provide a PR for the changes in Eleventy tomorrow.

**Comment by zachleat** [comment]
Shipping with Dev Server v2.0.2

**Comment by zachleat** [comment]
I’ll revisit the other changes to your original PR now—thanks!

**Comment by VividVisions** [comment]
Thank you so much!!

FYI: Using Node < v19, if one presses Ctrl-C  _immediately_ after making a request to the DevServer, there's a chance the shutdown will take several seconds when the request came through a connection with `keep-alive` (the default [`server.keepAliveTimeout`](https://nodejs.org/docs/latest-v22.x/api/http.html#serverkeepalivetimeout) is 5s).

We could easily prevent this at least for Node ≧ v18.2.0 by calling [`server.closeIdleConnections()`](https://nodejs.org/docs/latest/api/http.html#servercloseidleconnections) after `server.close()`. I'd recommend that and would gladly provide a quick PR.

If you want to prevent this for even older versions of Node, we could track and close every connection ourselves or use a library like [http-terminator](https://github.com/gajus/http-terminator). I'll provide a PR for this too, if you want but I'm not sure whether it's worth it. Alternatively, we could just make `keepAliveTimeout` adjustable through `eleventyConfig.setServerOptions()` so that users of  Node < v18.2 can set it to 1 or 2 seconds.

What do you think?
