### ISSUE TITLE
Bug: DOM diffing (Eleventy Dev server) doesn't recognize (declarative?) shadow DOM changes 

### ISSUE THREAD

**Issue by LeaVerou** [11ty/eleventy-dev-server#90]
I have a shortcode that uses declarative shadow DOM to scope its contents (I use it to have HTML figures).
E.g. 

```njk
{% scoped %}
<link rel="figures/foo/style.css" />
<!-- some html -->
{% endscoped %}
```

which becomes:

```html
<div class="shadow-host">
	<template shadowrootmode="open">
		<link rel="figures/foo/style.css" />
		<!-- some html -->
	</template>
</div>
```

Changes to its content are never picked up by the dev server, even though they actually correspond to changes in the source file.

Presumably this is not specific to declarative shadow DOM; I’d imagine it extends to any shadow DOM.

Happy to share more code / create a reduced testcase next week if you can't reproduce.

**Comment by zachleat** [comment]
Shipping with Dev Server v2.0.3, in Eleventy core v3.0.0-beta.2 v3.0.0-alpha.19
