### ISSUE TITLE
Send <0.19.0 has moderate XSS vulnerability

### ISSUE THREAD

**Issue by bu-michael** [11ty/eleventy-dev-server#91]
Send in version 0.18.0 is used in this project https://github.com/11ty/eleventy-dev-server/blob/main/package.json#L50 . This version has a moderate XSS vulnerability: https://github.com/advisories/GHSA-m6fv-jmcg-4jfg

Please update to a version > 0.19.0.

**Comment by zachleat** [comment]
Shipped with 2.0.4 thank you!
